name: '10K XP Daily'
run-name: 'Your study script is Active! Click to see status.'

on:
  schedule:
    - cron: '0 1 * * *' 
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
        
      - run: npm install node-fetch
        

      - run: node index.js
        env:
          LESSONS: 50 
          TOKEN: ${{ secrets.TOKEN }} 
